Tracker:AddLocations("locations/BOB.json")
Tracker:AddLocations("locations/WF.json")
Tracker:AddLocations("locations/JRB.json")
Tracker:AddLocations("locations/CCM.json")
Tracker:AddLocations("locations/BBH.json")
Tracker:AddLocations("locations/HMC.json")
Tracker:AddLocations("locations/LLL.json")
Tracker:AddLocations("locations/SSL.json")
Tracker:AddLocations("locations/DDD.json")
Tracker:AddLocations("locations/SL.json")
Tracker:AddLocations("locations/WDW.json")
Tracker:AddLocations("locations/TTM.json")
Tracker:AddLocations("locations/THI.json")
Tracker:AddLocations("locations/TTC.json")
Tracker:AddLocations("locations/RR.json")
Tracker:AddLocations("locations/Bowser.json")
Tracker:AddLocations("locations/Caps.json")
Tracker:AddLocations("locations/Castle.json")
Tracker:AddLocations("locations/Secrets.json")
Tracker:AddMaps("maps/courses.json")

Tracker:AddItems("items/caps.json")
Tracker:AddItems("items/cannons.json")
Tracker:AddItems("items/keys.json")
Tracker:AddItems("items/stars.json")
Tracker:AddItems("items/settings.json")

Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/settings.json")
Tracker:AddLayouts("layouts/layout.json")
Tracker:AddLayouts("layouts/tracker.json")

ScriptHost:LoadScript("scripts/logic.lua")
if PopVersion and PopVersion >= "0.18.0" then
    ScriptHost:LoadScript("scripts/archipelago.lua")
end